"""
ZeroPhish Repository Protocols & Domain Interfaces.
Lightweight Python Protocols defining clear data-access seams.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional, Protocol, runtime_checkable

if TYPE_CHECKING:
    from analytics.models import (
        AdminDashboardSummary,
        FalsePositiveReport,
        ModelMetrics,
        PolicyRule,
        ThreatFeedItem,
        ThreatHeatmapEntry,
    )
    from auth.models import User, UserInDB, UserRole, UserUpdate
    from incidents.models import (
        Incident,
        IncidentComment,
        IncidentSeverity,
        IncidentStatus,
        IncidentUpdate,
    )
    from webhooks.models import WebhookDelivery, WebhookSubscription


@runtime_checkable
class UserRepository(Protocol):
    def get_by_id(self, user_id: str) -> Optional[Any]: ...
    def get_by_email(self, email: str) -> Optional[Any]: ...
    def save(self, user: Any) -> Any: ...
    def list_all(self, role: Optional[Any] = None) -> List[Any]: ...
    def update(self, user_id: str, update: Any) -> Optional[Any]: ...
    def delete(self, user_id: str) -> bool: ...
    def store_token(self, token: str, user_id: str, expires_at: float) -> None: ...
    def validate_token(self, token: str) -> Optional[Any]: ...
    def revoke_token(self, token: str) -> None: ...
    def increment_scan(self, user_id: str, final_score: float) -> None: ...


@runtime_checkable
class IncidentRepository(Protocol):
    def save(self, incident: Any) -> Any: ...
    def get_by_id(self, incident_id: str) -> Optional[Any]: ...
    def list_all(
        self,
        status: Optional[Any] = None,
        severity: Optional[Any] = None,
        assignee_id: Optional[str] = None,
        reporter_id: Optional[str] = None,
    ) -> List[Any]: ...
    def update(self, incident_id: str, update: Any) -> Optional[Any]: ...
    def add_comment(self, incident_id: str, comment: Any) -> Optional[Any]: ...
    def delete(self, incident_id: str) -> bool: ...
    def stats(self) -> Dict[str, Any]: ...


@runtime_checkable
class AnalyticsRepository(Protocol):
    def record_scan_event(self, event: Dict[str, Any]) -> None: ...
    def get_scan_events(self, limit: int = 10000) -> List[Dict[str, Any]]: ...
    def get_dashboard_summary(self) -> Any: ...
    def get_threat_heatmap(self) -> List[Any]: ...
    def get_threat_feed(self, limit: int = 50) -> List[Any]: ...
    def get_model_metrics(self) -> Any: ...
    def update_model_metrics(self, fp_delta: int = 0, fn_delta: int = 0) -> None: ...
    def save_false_positive(self, report: Any) -> Any: ...
    def list_false_positives(self, reviewed: Optional[bool] = None) -> List[Any]: ...
    def review_false_positive(
        self, fp_id: str, reviewer_id: str, resolution: str
    ) -> Optional[Any]: ...
    def save_policy_rule(self, rule: Any) -> Any: ...
    def list_policy_rules(self) -> List[Any]: ...
    def delete_policy_rule(self, rule_id: str) -> bool: ...


@runtime_checkable
class WebhookRepository(Protocol):
    def save_subscription(self, subscription: Any) -> Any: ...
    def get_subscription(self, sub_id: str) -> Optional[Any]: ...
    def list_subscriptions(self, owner_id: Optional[str] = None) -> List[Any]: ...
    def delete_subscription(self, sub_id: str, owner_id: Optional[str] = None) -> bool: ...
    def record_delivery(self, delivery: Any) -> None: ...
    def get_delivery_log(self, limit: int = 100) -> List[Any]: ...


@runtime_checkable
class ScanResultRepository(Protocol):
    def save(self, scan_id: str, scan_data: Any) -> None: ...
    def get(self, scan_id: str) -> Optional[Any]: ...
    def delete(self, scan_id: str) -> bool: ...
    def list_all(self, limit: int = 100) -> List[Any]: ...
    def count(self) -> int: ...
    def count_pending(self) -> int: ...


@runtime_checkable
class CacheBackend(Protocol):
    async def get(self, key: str) -> Optional[str]: ...
    async def set(self, key: str, value: str, ttl_seconds: Optional[int] = None) -> None: ...
    async def delete(self, key: str) -> bool: ...
    async def clear_prefix(self, prefix: str) -> int: ...
    async def get_stats(self) -> Dict[str, Any]: ...
