packages:
  - 'Frontend'

allowBuilds:
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  '@types/react': '19.2.7'
  '@types/react-dom': '19.2.3'
